// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  media_row: dynamic(() => import("./MediaRow")),
  video: dynamic(() => import("./Video")),
};
